### ISSUE TITLE
Feature extraction for skating videos

### ISSUE THREAD

**Issue by saniazahan** [MahdiNek/EAGLE-Eye#1]
Hi 
Could you tell me how did you extract features for skating? As it has 5824 frames and C3D expects 16 frames. Did you average the output from f6 layer C3D or something else? I would really appreciate it if you could explain how you handled the huge number of frames. I read your paper but could not find any info about it. Thanks.

**Comment by MahdiNek** [comment]
Hello Sania,

The whole video is comprised of some 16-frame clips. Each clip is fed to the C3D network and the resulted features are concatenated across the temporal dimension. BTW, you may find more details regarding the implementations in the "supplementary material" file.

Regards,
Mahdiar

**Comment by saniazahan** [comment]
Hi Mahdiar
 
Thank you so much for your prompt reply. I would definitely go through supplementary for details.
